import {Product} from "./types";

export const PRODUCTS: {[key: number]: Product} =
  {
  1: {
    id: 1,
    name: 'Wireless Headphones',
    code: 'WH-001',
    description: 'Bluetooth wireless headphones with noise cancellation.',
    price: 120,
    salePrice: 108, // 10% discount applied
    onSale: false,
    category: 'Electronics',
    quantity: 15,
  },
  2: {
    id: 2,
    name: 'Gaming Mouse',
    code: 'GM-002',
    description: 'High-precision gaming mouse with RGB lighting.',
    price: 45,
    salePrice: 40.5,
    onSale: true,
    category: 'Electronics',
    quantity: 30,

  },
  3: {
    id: 3,
    name: 'Mechanical Keyboard',
    code: 'MK-003',
    description: 'Mechanical keyboard with blue switches.',
    price: 85,
    salePrice: 76.5,
    onSale: true,
    category: 'Electronics',
    quantity: 20,
  },
  4: {
    id: 4,
    name: '4K Monitor',
    code: '4KM-004',
    description: '27-inch 4K UHD monitor with HDR support.',
    price: 350,
    salePrice: 315,
    onSale: true,
    category: 'Electronics',
    quantity: 10,
  },
  5: {
    id: 5,
    name: 'USB-C Hub',
    code: 'UCH-005',
    description: '7-in-1 USB-C hub with HDMI and Ethernet.',
    price: 60,
    salePrice: 54,
    onSale: false,
    category: 'Accessories',
    quantity: 50,
  },
  6: {
    id: 6,
    name: 'Portable SSD',
    code: 'PSSD-006',
    description: '1TB portable SSD with USB 3.1 connectivity.',
    price: 150,
    salePrice: 135,
    onSale: false,
    category: 'Storage',
    quantity: 25,
  },
  7: {
    id: 7,
    name: 'Smartphone Stand',
    code: 'SS-007',
    description: 'Adjustable aluminum smartphone stand.',
    price: 20,
    salePrice: 18,
    onSale: false,
    category: 'Accessories',
    quantity: 100,
  },
  8: {
    id: 8,
    name: 'Wireless Charger',
    code: 'WC-008',
    description: 'Fast wireless charger compatible with Qi-enabled devices.',
    price: 35,
    salePrice: 31.5,
    onSale: false,
    category: 'Accessories',
    quantity: 40,
  },
  9: {
    id: 9,
    name: 'Noise-Canceling Earbuds',
    code: 'NCE-009',
    description: 'false wireless earbuds with active noise cancellation.',
    price: 99,
    salePrice: 89.1,
    onSale: false,
    category: 'Electronics',
    quantity: 60,
  },
  10: {
    id: 10,
    name: 'Laptop Backpack',
    code: 'LB-010',
    description: 'Water-resistant backpack with padded laptop compartment.',
    price: 70,
    salePrice: 63,
    onSale: false,
    category: 'Accessories',
    quantity: 35,
  },
  11: {
    id: 11,
    name: 'Fitness Tracker',
    code: 'FT-011',
    description: 'Fitness tracker with heart rate monitor and GPS.',
    price: 130,
    salePrice: 117,
    onSale: false,
    category: 'Wearables',
    quantity: 45,
  },
  12: {
    id: 12,
    name: 'Smartwatch',
    code: 'SW-012',
    description: 'Smartwatch with customizable watch faces and apps.',
    price: 250,
    salePrice: 225,
    onSale: false,
    category: 'Wearables',
    quantity: 22,
  },
  13: {
    id: 13,
    name: 'Action Camera',
    code: 'AC-013',
    description: '4K action camera with waterproof case.',
    price: 200,
    salePrice: 180,
    onSale: false,
    category: 'Electronics',
    quantity: 18,
  },
  14: {
    id: 14,
    name: 'Bluetooth Speaker',
    code: 'BS-014',
    description: 'Portable Bluetooth speaker with 360-degree sound.',
    price: 80,
    salePrice: 72,
    onSale: false,
    category: 'Electronics',
    quantity: 55,
  },
  15: {
    id: 15,
    name: 'Drone',
    code: 'DR-015',
    description: 'Quadcopter drone with 1080p camera and GPS.',
    price: 300,
    salePrice: 270,
    onSale: false,
    category: 'Electronics',
    quantity: 12,
  },
  16: {
    id: 16,
    name: 'VR Headset',
    code: 'VRH-016',
    description: 'Virtual reality headset compatible with PC and consoles.',
    price: 400,
    salePrice: 360,
    onSale: false,
    category: 'Electronics',
    quantity: 8,
  },
  17: {
    id: 17,
    name: 'Electric Toothbrush',
    code: 'ET-017',
    description: 'Rechargeable electric toothbrush with multiple modes.',
    price: 60,
    salePrice: 54,
    onSale: false,
    category: 'Personal Care',
    quantity: 70,
  },
  18: {
    id: 18,
    name: 'Hair Dryer',
    code: 'HD-018',
    description: 'Ionic hair dryer with diffuser and concentrator attachments.',
    price: 45,
    salePrice: 40.5,
    onSale: false,
    category: 'Personal Care',
    quantity: 25,
  },
  19: {
    id: 19,
    name: 'Espresso Machine',
    code: 'EM-019',
    description: 'Automatic espresso machine with milk frother.',
    price: 500,
    salePrice: 450,
    onSale: false,
    category: 'Kitchen Appliances',
    quantity: 5,
  },
  20: {
    id: 20,
    name: 'Air Fryer',
    code: 'AF-020',
    description: '5.8-quart air fryer with digital touchscreen.',
    price: 120,
    salePrice: 108,
    onSale: false,
    category: 'Kitchen Appliances',
    quantity: 15,
  },
  21: {
    id: 21,
    name: 'Robot Vacuum',
    code: 'RV-021',
    description: 'Wi-Fi connected robot vacuum with mapping technology.',
    price: 350,
    salePrice: 315,
    onSale: false,
    category: 'Home Appliances',
    quantity: 10,
  },
  22: {
    id: 22,
    name: 'Electric Scooter',
    code: 'ES-022',
    description: 'Foldable electric scooter with 15-mile range.',
    price: 300,
    salePrice: 270,
    onSale: false,
    category: 'Transportation',
    quantity: 8,
  },
  23: {
    id: 23,
    name: 'Digital Camera',
    code: 'DC-023',
    description: 'Mirrorless digital camera with 24MP sensor.',
    price: 800,
    salePrice: 720,
    onSale: false,
    category: 'Photography',
    quantity: 6,
  },
  24: {
    id: 24,
    name: 'Tripod',
    code: 'TP-024',
    description: 'Lightweight aluminum tripod for cameras.',
    price: 50,
    salePrice: 45,
    onSale: false,
    category: 'Photography',
    quantity: 40,
  },
  25: {
    id: 25,
    name: 'Graphics Tablet',
    code: 'GT-025',
    description: 'Graphics drawing tablet with pen pressure sensitivity.',
    price: 250,
    salePrice: 225,
    onSale: false,
    category: 'Computers',
    quantity: 14,
  },
  26: {
    id: 26,
    name: 'Smart Light Bulb',
    code: 'SLB-026',
    description: 'Wi-Fi enabled smart light bulb with color-changing feature.',
    price: 25,
    salePrice: 22.5,
    onSale: false,
    category: 'Home Automation',
    quantity: 80,
  },
  27: {
    id: 27,
    name: 'Electric Kettle',
    code: 'EK-027',
    description: '1.7-liter electric kettle with temperature control.',
    price: 70,
    salePrice: 63,
    onSale: false,
    category: 'Kitchen Appliances',
    quantity: 30,
  },
  28: {
    id: 28,
    name: 'Standing Desk',
    code: 'SD-028',
    description: 'Height-adjustable standing desk with memory settings.',
    price: 400,
    salePrice: 360,
    onSale: false,
    category: 'Furniture',
    quantity: 5,
  },
  29: {
    id: 29,
    name: 'Office Chair',
    code: 'OC-029',
    description: 'Ergonomic office chair with lumbar support.',
    price: 150,
    salePrice: 135,
    onSale: false,
    category: 'Furniture',
    quantity: 20,
  },
  30: {
    id: 30,
    name: 'Electric Guitar',
    code: 'EG-030',
    description: 'Solid-body electric guitar with maple neck.',
    price: 600,
    salePrice: 540,
    onSale: false,
    category: 'Musical Instruments',
    quantity: 7,
  },
};
